# Configuration for Antrea-NSX Adapter
# List of NSX Manager IPs
nsxManagers:
  - "10.1.1.24"
# Optional. If not defined, nsxSvcLoadBalancerIP will be allocated from the Supervisor's loadBalancer IP pool.
# If it's defined, it should be in the range defined in the Supervisor's loadBalancer IP pool.
# It is the proxyIP which is used by Antrea-NSX adapter in TKG workload cluster to reach NSX manager.
nsxSvcLoadBalancerIP: ""
