apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avisvcingress
  labels:
    run: nginx
  annotations:
    kubernetes.io/ingress.class: avi
spec:
  rules:
    - host: app.site-a.vcf.lab
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ingress-svc
                port:
                  number: 80