cache:
  enabled: false
  expireHours: 24
concurrentRequestLimit:
  registry:
    enabled: false
    max: 500
core:
  replicas: 1
  secret: VMware123!VMware123!
  xsrfKey: 0123456789ABCDEF0123456789ABCDEF
createNetworkPolicy: false
database:
  password: VMware123!VMware123!
  type: internal
enableContourHttpProxy: false
enableNginxLoadBalancer: true
harborAdminPassword: VMware123!
hostname: harbor-vks-cl.vcf.sddc.lab
jobservice:
  replicas: 1
  secret: VMware123!VMware123!
logLevel: info
metrics:
  core:
    path: /metrics
    port: 8001
  enabled: false
  exporter:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
namespace: tanzu-system-registry
network:
  ipFamilies: []
persistence:
  persistentVolumeClaim:
    database:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 1Gi
      storageClass: "vks-storage-policy"
      subPath: ""
    jobservice:
      jobLog:
        accessMode: ReadWriteOnce
        existingClaim: ""
        size: 1Gi
        storageClass: "vks-storage-policy"
        subPath: ""
    redis:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 1Gi
      storageClass: "vks-storage-policy"
      subPath: ""
    registry:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 10Gi
      storageClass: "vks-storage-policy"
      subPath: ""
    trivy:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 5Gi
      storageClass: "vks-storage-policy"
      subPath: ""
port:
  https: 443
proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: 127.0.0.1,localhost,.local,.internal
redis:
  type: internal
registry:
  replicas: 1
  secret: VMware123!VMware123!
#resources:
#  containers:
#    - cpuLimit: 1000m
#      cpuRequest: 500m
#      memoryLimit: 2Gi
#      memoryRequest: 512Mi
#      name: core
#    - cpuLimit: 2000m
#      cpuRequest: 1000m
#      memoryLimit: 2Gi
#      memoryRequest: 1Gi
#      name: database
#    - cpuLimit: 1000m
#      cpuRequest: 500m
#      memoryLimit: 2Gi
#      memoryRequest: 512Mi
#      name: jobservice
#    - cpuLimit: 300m
#      cpuRequest: 100m
#      memoryLimit: 256Mi
#      memoryRequest: 128Mi
#      name: portal
#    - cpuLimit: 500m
#      cpuRequest: 200m
#      memoryLimit: 1Gi
#      memoryRequest: 256Mi
#      name: redis
#    - cpuLimit: 1000m
#      cpuRequest: 500m
#      memoryLimit: 2Gi
#      memoryRequest: 512Mi
#      name: registry
#    - cpuLimit: 500m
#      cpuRequest: 200m
#      memoryLimit: 512Mi
#      memoryRequest: 256Mi
#      name: registryctl
#    - cpuLimit: 2000m
#      cpuRequest: 500m
#      memoryLimit: 4Gi
#      memoryRequest: 1Gi
#      name: trivy
#    - cpuLimit: 300m
#      cpuRequest: 100m
#      memoryLimit: 256Mi
#      memoryRequest: 128Mi
#      name: exporter
#  namespaceLimitRange:
#    defaultCPULimit: 1000m
#    defaultCPURequest: 300m
#    defaultMemoryLimit: 2Gi
#    defaultMemoryRequest: 256Mi
secretKey: 0123456789ABCDEF
tlsCertificate:
  tlsSecretLabels: {"managed-by": "vmware-vRegistry"}
#  signingSettings:
#    additionalDnsNames: []
#    ipAddresses: []
trace:
  enabled: false
  jaeger:
    endpoint: http://hostname:14268/api/traces
  otel:
    compression: false
    endpoint: hostname:4318
    insecure: true
    timeout: 10
    url_path: /v1/traces
  provider: jaeger
  sample_rate: 1
trivy:
  dbRepository: ghcr.io/aquasecurity/trivy-db
  enabled: true
  gitHubToken: ""
  insecure: false
  javaDBRepository: ghcr.io/aquasecurity/trivy-java-db
  offlineScan: false
  replicas: 1
  skipJavaDBUpdate: false
  skipUpdate: false
  timeout: ""
  tmpdir: ""
vmciRelayProxy:
  enabled: false
